/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Num = 5;
  /** RegularExpression Id. */
  int PLUS = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int TIMES = 8;
  /** RegularExpression Id. */
  int DIV = 9;
  /** RegularExpression Id. */
  int LPAR = 10;
  /** RegularExpression Id. */
  int RPAR = 11;
  /** RegularExpression Id. */
  int EL = 12;
  /** RegularExpression Id. */
  int let = 13;
  /** RegularExpression Id. */
  int LAMBDA = 14;
  /** RegularExpression Id. */
  int FUNCTION_ARROW = 15;
  /** RegularExpression Id. */
  int BINDING = 16;
  /** RegularExpression Id. */
  int COLON = 17;
  /** RegularExpression Id. */
  int ASSIGNMENT = 18;
  /** RegularExpression Id. */
  int IN = 19;
  /** RegularExpression Id. */
  int END = 20;
  /** RegularExpression Id. */
  int function = 21;
  /** RegularExpression Id. */
  int COMMA = 22;
  /** RegularExpression Id. */
  int REFERENCE = 23;
  /** RegularExpression Id. */
  int DEREFERENCE = 24;
  /** RegularExpression Id. */
  int SEQUENCE = 25;
  /** RegularExpression Id. */
  int WHILE = 26;
  /** RegularExpression Id. */
  int DO = 27;
  /** RegularExpression Id. */
  int BOOLVALUE = 28;
  /** RegularExpression Id. */
  int INT = 29;
  /** RegularExpression Id. */
  int BOOL = 30;
  /** RegularExpression Id. */
  int REF = 31;
  /** RegularExpression Id. */
  int EQUAL = 32;
  /** RegularExpression Id. */
  int NOT_EQUAL = 33;
  /** RegularExpression Id. */
  int GREATER = 34;
  /** RegularExpression Id. */
  int GREATEROREQUAL = 35;
  /** RegularExpression Id. */
  int SMALLER = 36;
  /** RegularExpression Id. */
  int SMALLEROREQUAL = 37;
  /** RegularExpression Id. */
  int AND = 38;
  /** RegularExpression Id. */
  int OR = 39;
  /** RegularExpression Id. */
  int NOT = 40;
  /** RegularExpression Id. */
  int IF = 41;
  /** RegularExpression Id. */
  int THEN = 42;
  /** RegularExpression Id. */
  int ELSE = 43;
  /** RegularExpression Id. */
  int Id = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<Num>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\";;\"",
    "\"let\"",
    "\"=>\"",
    "\"->\"",
    "\"=\"",
    "\":\"",
    "<ASSIGNMENT>",
    "\"in\"",
    "\"end\"",
    "\"function\"",
    "\",\"",
    "\"new\"",
    "\"!\"",
    "\";\"",
    "\"while\"",
    "\"do\"",
    "<BOOLVALUE>",
    "\"int\"",
    "\"bool\"",
    "\"ref\"",
    "\"==\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"&&\"",
    "\"||\"",
    "\"~\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "<Id>",
  };

}
