/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int QUOTED = 5;
  /** RegularExpression Id. */
  int Num = 6;
  /** RegularExpression Id. */
  int DOT = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int RECORD_BEGIN = 9;
  /** RegularExpression Id. */
  int RECORD_END = 10;
  /** RegularExpression Id. */
  int MINUS = 11;
  /** RegularExpression Id. */
  int TIMES = 12;
  /** RegularExpression Id. */
  int DIV = 13;
  /** RegularExpression Id. */
  int LPAR = 14;
  /** RegularExpression Id. */
  int RPAR = 15;
  /** RegularExpression Id. */
  int EL = 16;
  /** RegularExpression Id. */
  int let = 17;
  /** RegularExpression Id. */
  int PRINTLN = 18;
  /** RegularExpression Id. */
  int LAMBDA = 19;
  /** RegularExpression Id. */
  int FUNCTION_ARROW = 20;
  /** RegularExpression Id. */
  int BINDING = 21;
  /** RegularExpression Id. */
  int COLON = 22;
  /** RegularExpression Id. */
  int ASSIGNMENT = 23;
  /** RegularExpression Id. */
  int IN = 24;
  /** RegularExpression Id. */
  int END = 25;
  /** RegularExpression Id. */
  int function = 26;
  /** RegularExpression Id. */
  int COMMA = 27;
  /** RegularExpression Id. */
  int REFERENCE = 28;
  /** RegularExpression Id. */
  int DEREFERENCE = 29;
  /** RegularExpression Id. */
  int SEQUENCE = 30;
  /** RegularExpression Id. */
  int WHILE = 31;
  /** RegularExpression Id. */
  int DO = 32;
  /** RegularExpression Id. */
  int BOOLVALUE = 33;
  /** RegularExpression Id. */
  int INT = 34;
  /** RegularExpression Id. */
  int BOOL = 35;
  /** RegularExpression Id. */
  int REF = 36;
  /** RegularExpression Id. */
  int STRING = 37;
  /** RegularExpression Id. */
  int EQUAL = 38;
  /** RegularExpression Id. */
  int NOT_EQUAL = 39;
  /** RegularExpression Id. */
  int GREATER = 40;
  /** RegularExpression Id. */
  int GREATEROREQUAL = 41;
  /** RegularExpression Id. */
  int SMALLER = 42;
  /** RegularExpression Id. */
  int SMALLEROREQUAL = 43;
  /** RegularExpression Id. */
  int AND = 44;
  /** RegularExpression Id. */
  int OR = 45;
  /** RegularExpression Id. */
  int NOT = 46;
  /** RegularExpression Id. */
  int IF = 47;
  /** RegularExpression Id. */
  int THEN = 48;
  /** RegularExpression Id. */
  int ELSE = 49;
  /** RegularExpression Id. */
  int Id = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<QUOTED>",
    "<Num>",
    "\".\"",
    "\"+\"",
    "\"[\"",
    "\"]\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\";;\"",
    "\"let\"",
    "\"println\"",
    "\"=>\"",
    "\"->\"",
    "\"=\"",
    "\":\"",
    "<ASSIGNMENT>",
    "\"in\"",
    "\"end\"",
    "\"function\"",
    "\",\"",
    "\"new\"",
    "\"!\"",
    "\";\"",
    "\"while\"",
    "\"do\"",
    "<BOOLVALUE>",
    "\"int\"",
    "\"bool\"",
    "\"ref\"",
    "\"string\"",
    "\"==\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"&&\"",
    "\"||\"",
    "\"~\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "<Id>",
  };

}
